### ISSUE TITLE
Permanent watch

### ISSUE THREAD

**Issue by Noumcreation** [ellerbrock/docker-collection#4]
You've done a great sass container.
I was wondering if there was anyway to have it up and runing to watch for modifications while working ?

**Comment by ellerbrock** [comment]
hi @Noumcreation,

to be honest i haven't used it for a while but i think i have it implemented.
You can have a look at the [gulpfile.js](https://github.com/ellerbrock/docker-collection/blob/e62dce8155967468305882b28a0ee430a0990c8e/dockerfiles/alpine-gulp-sass/src/gulpfile.js#L29) here:


here my docker-compose file with some settings of a older project from me where i used it:

```
services:

  hugo:
    image: ellerbrock/alpine-hugo:latest
    command: server --bind 0.0.0.0 -w
    volumes:
      - ${DIR_HUGO_DEV}:/site
    ports:
      - ${PORT_HUGO}:1313
    networks:
      - webdev

  gulp:
    image: ellerbrock/alpine-gulp-sass
    volumes:
      - ${DIR_SASS}:/site/sass
      - ${DIR_CSS}:/site/css
    environment:
      - SASS=${FILES_SASS}
      - GULP_DEBUG=${GULP_DEBUG}
    command: [ "gulp", "sass:watch" ]
    stdin_open: true
    tty: true
    entrypoint: ash
    depends_on:
      - hugo
    networks:
      - webdev

networks:
  webdev:
    driver: bridge
```

Hope this may help you ...

Cheers Maik
